OrderFood/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using OrderFood.Core.Models;
using OrderFood.DAL;
using OrderFood.DAL.DbContext;
using OrderFood.Domain.Dtos;
using OrderFood.Domain.Services;
using Microsoft.AspNetCore.Mvc;

namespace OrderFood.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IOrderService _orderService;

        public OrderController(
                   ApplicationDbContext context,
                   IUnitOfWorkFactory unitOfWorkFactory,
                   IOrderService orderService)
        {
            if (context == null)
                throw new ArgumentNullException(nameof(context));
            if (unitOfWorkFactory == null)
                throw new ArgumentNullException(nameof(unitOfWorkFactory));
           if (orderService == null)
               throw new ArgumentNullException(nameof(orderService));

            _context = context;
            _unitOfWorkFactory = unitOfWorkFactory;
            _orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? restaurantId, int? userId)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var orders = unitOfWork.Order.GetAll().Where(x=>x.RestaurantId==restaurantId.Value && x.UserId==userId.Value && x.isClosed!=true);
                return View(orders);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create(int? id, int? restaurantId, int? userId )
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }
                if (!restaurantId.HasValue)
                {
                    return NotFound();
                }

                var order = unitOfWork.Order.GetAll().Where(x=>x.FoodId==id && x.RestaurantId==restaurantId && x.UserId==userId && x.isClosed==false).FirstOrDefault();
                if (order == null)
                {
                    order = new Order();
                    order.Count = 1;
                    order.RestaurantId = restaurantId.Value;
                    order.FoodId = id.Value;
                    order.UserId = userId.Value;
                    var result = await _orderService.AddOrderAsync(order);
                    return RedirectToAction("Index", new { restaurantId = restaurantId.Value,userId=userId.Value });
                }
                else
                {
                    order.Count = order.Count + 1;
                    unitOfWork.Order.Update(order);
                    await unitOfWork.CompleteAsync();
                    return RedirectToAction("Index", new { restaurantId = restaurantId.Value, userId=userId.Value });
                }
         

            }
        }
    }
}

OrderFood/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using OrderFood.Core.Models;
using OrderFood.DAL;
using OrderFood.DAL.DbContext;
using OrderFood.Domain.Dtos;
using OrderFood.Domain.Services;
using Microsoft.AspNetCore.Mvc;

namespace OrderFood.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class RatingController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IRatingService _ratingService;

        public RatingController(
                   ApplicationDbContext context,
                   IUnitOfWorkFactory unitOfWorkFactory,
                   IRatingService ratingService)
        {
            if (context == null)
                throw new ArgumentNullException(nameof(context));
            if (unitOfWorkFactory == null)
                throw new ArgumentNullException(nameof(unitOfWorkFactory));
           if (ratingService == null)
               throw new ArgumentNullException(nameof(ratingService));

            _context = context;
            _unitOfWorkFactory = unitOfWorkFactory;
            _ratingService = ratingService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? restaurantId, int? userId)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var orders = unitOfWork.Order.GetAll().Where(x=>x.RestaurantId==restaurantId.Value && x.UserId==userId.Value && x.isClosed!=true);
                return View(orders);
            }
        }

        [HttpPost]
        public async Task<IActionResult> setMark([FromForm] Rating rating )
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (rating.UserId==0)
                {
                    return NotFound();
                }
                if (rating.RestaurantId == 0)
                {
                    return NotFound();
                }
                var ratingInDb=unitOfWork.Rating.GetAll().Where(x => x.RestaurantId == rating.RestaurantId).FirstOrDefault();
                if (ratingInDb!= null) {
                ratingInDb.Mark = rating.Mark;
                unitOfWork.Rating.Update(ratingInDb);
                await unitOfWork.CompleteAsync();
                }
                else
                {
                    var result = await _ratingService.CreateRatingAsync(rating);
                }
                return RedirectToAction("Details", "Restaurant", new { id = rating.RestaurantId});
            }
        }
    }
}

OrderFood/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OrderFood.DAL;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

using OrderFood.DAL.DbContext;
using OrderFood.Domain.Services;
using OrderFood.Core.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace OrderFood.Controllers
{
    [Authorize(Roles="Admin,Client")]
    public class RestaurantController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IRestaurantService _restaurantService;
        private readonly ICommentService _commentService;
        IHostingEnvironment _appEnvironment;

        public RestaurantController(ApplicationDbContext context, 
                                    IUnitOfWorkFactory unitOfWorkFactory, 
                                    IHostingEnvironment appEnvironment,
                                    IRestaurantService restaurantService,
                                    ICommentService commentService)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
            _appEnvironment = appEnvironment;
            _context = context;
            _restaurantService = restaurantService;
            _commentService = commentService;
        }

        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var restaurants = unitOfWork.Restaurants.GetAll().Where(x => x.Name != null);
               
                return View(restaurants);
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var model = new Restaurant
                {
                    Name = "",
                    Description = ""
                };
                
                return View(model);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Restaurant restaurant, IFormFile uploadedFile)
        {
          if (uploadedFile != null)
                    {
                        // путь к папке Files
                        string path = "/images/" + uploadedFile.FileName;
                        // сохраняем файл в папку Files в каталоге wwwroot
                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await uploadedFile.CopyToAsync(fileStream);
                        }
                        restaurant.Image =uploadedFile.FileName;
                    }
            var result = await _restaurantService.CreateFoodAsync(restaurant);

            if (result.IsSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var resultError in result.Errors)
                {
                    ModelState.AddModelError("Error", resultError);
                }
             
                return View(restaurant);
            }
        }

        // GET: 
        public async Task<IActionResult> Details(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var restaurant = unitOfWork.Restaurants.GetById(id.Value);
                if (restaurant == null)
                {
                    return NotFound();
                }
                
                return View(restaurant);
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var restaurant = unitOfWork.Restaurants.GetById(id.Value);
                return View(restaurant);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Restaurant restaurant,IFormFile uploadedFile)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                ValidatePosData(unitOfWork, restaurant.Name);
                if (ModelState.IsValid)
                {
                    if (uploadedFile != null)
                    {
                        // путь к папке Files
                        string path = "/images/" + uploadedFile.FileName;
                        // сохраняем файл в папку Files в каталоге wwwroot
                        using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                        {
                            await uploadedFile.CopyToAsync(fileStream);
                        }
                        restaurant.Image =uploadedFile.FileName;
                    }
                    unitOfWork.Restaurants.Update(restaurant);
                    await unitOfWork.CompleteAsync();

                    return RedirectToAction(nameof(Index));
                }
               
                return View(restaurant);
            }
        }
        private void ValidatePosData(IUnitOfWork unitOfWork, string name)
        {
            var pos = unitOfWork.Food.GetByName(name);

            if (pos != null)
                ModelState.AddModelError("Error", $"Пункт с названием {name} уже существует");
        }


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddComment( Comment comment)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (comment.UserId == 0)
                {
                    return NotFound();
                }
                if (comment.RestaurantId == 0)
                {
                    return NotFound();
                }

                var result = await _commentService.CreateCommentAsync(comment);
                return RedirectToAction("Index", "Restaurant", new { id = comment.RestaurantId });
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants
                .Include(p => p.Food)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restaurant = await _context.Restaurants.FindAsync(id);
            _context.Restaurants.Remove(restaurant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(int id)
        {
            return _context.Restaurants.Any(e => e.Id == id);
        }

    }
}

OrderFood/Views/Restaurant/Create.cshtml
@model OrderFood.Core.Models.Restaurant;

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Restaurant" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" name="uploadedFile" /><br>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OrderFood/Views/Restaurant/Delete.cshtml
@model OrderFood.Core.Models.Restaurant

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Food</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

OrderFood/Views/Restaurant/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@model OrderFood.Core.Models.Restaurant

@{
    ViewData["Title"] = "Details";
    var restaurantId = Html.Raw(Model.Id);
    var img1 = "/images/" + Model.Image;
    int userId = Convert.ToInt32(UserManager.GetUserId(User));
    var curUser = "";
    decimal avgRating = 0;
    int countRating = Model.Ratings.Count;

}




<div>
    <h4>Заведение</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            <img src=@img1 alt="Image" />
        </dd>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>

<hr />
<h3>Список блюд</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Наименование
            </th>
            <th>
                Цена
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Food)
        {
        <tr>
            <td>
                @item.Name
            </td>
            <td>
                @item.Price
            </td>
            @if (User.IsInRole("Client"))
            {
                <td>
                    <a asp-controller="Order" asp-action="Create" asp-route-id="@item.Id" asp-route-restaurantId="@restaurantId" asp-route-userId="@userId">Добавить в корзину</a>
                </td>
            }

            </tr>


        }
    </tbody>
</table>
<hr />
<h3>Рейтинг</h3>
<div>
    @foreach (var item in Model.Ratings)
    {
        avgRating += item.Mark;

    }
    @{
        if (countRating == 0) { avgRating = 0; }
        else { avgRating = avgRating / countRating; }
    }
    <dl class="row">
        <dt class="col-sm-2">
            Средняя оценка
        </dt>
        <dd class="col-sm-10">
            @avgRating
        </dd>
    </dl>

    @if (User.IsInRole("Client"))
    {

        <form method="post" asp-action="setMark" asp-controller="Rating">
            <select name="mark">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            <input type="hidden" asp-for="@userId" />
            <input type="hidden" asp-for="@restaurantId" />
            <input type="submit" value="Отправить" />
        </form>

    }

    <hr />
    <h2> Комментарии</h2>
    <div>
        @foreach (var item in Model.Comments)
        {
            curUser = UserManager.Users.FirstOrDefault(u => u.Id == item.UserId).UserName;
            <dl class="row">
                <dt class="col-sm-2">
                    @curUser
                </dt>
                <dd class="col-sm-10">
                    @item.Text
                </dd>
            </dl>
        }
    </div>
        <hr />

        @if (User.IsInRole("Client"))
        {
            <div>
                <form asp-action="AddComment" method="post">
                    <div class="form-group">
                        <label asp-for="Comment" class="control-label"></label>
                        <br />
                        <textarea name="Text"> </textarea>
                    </div>

                    <input type="hidden" asp-for="@userId" />
                    <input type="hidden" asp-for="@restaurantId" />
                    <div class="form-group">
                        <input type="submit" value="Добавить комментарий" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        }

        <div>
            <a asp-action="Index">Back to List</a>
        </div>

OrderFood/Views/Restaurant/Edit.cshtml
@model OrderFood.Core.Models.Restaurant
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Edit</h1>
<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Restaurant" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" name="uploadedFile" /><br>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OrderFood/Views/Restaurant/Index.cshtml
@model IEnumerable<OrderFood.Core.Models.Restaurant>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@* Razor*@
<h2>Заведения</h2>
<table>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <h2> @Html.DisplayFor(modelItem => item.Name)</h2>
            </td>
            <td width="200"></td>
             <td>
                 <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
            @if (User.IsInRole("Admin"))
            {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>

            }
            </td>
        </tr>
    }
</table>
@if (User.IsInRole("Admin"))
{
    <a asp-action="Create">Create</a>
}